# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

value_1 = 1
value_2 = 2

sum_even = 0

while value_1 <= 4000000:
  if value_1 % 2 == 0: # check for even number
    sum_even += value_1 # add and equal
    value_next = value_1 + value_2 # eg 1 + 2 = 3
    value_1 = value_2 # eg value_1 is now = 2
    value_2 = value_next # eg value_2 is now 3
  
  # eg repeat, 2 + 3 = 5, etc.
print(sum_even)

# code is too slow, solution
limit=4000000 
sum=0
a=1
b=1
c=a+b
while c<limit
  sum=sum+c
  a=b+c # eg a= 1+1 =2
  b=c+a # eg b= 2+1 =3
  c=a+b # eg c= 2+3 =5
print(sum)
  
